# Generated by Django 4.1.7 on 2023-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='img_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='map_url',
            field=models.TextField(),
        ),
    ]
